[workspace]
members = ["src/struct", "src/common", "src/bytes"]
resolver = "2"

[workspace.dependencies]
candid = "0.10"
ic-cdk = "0.18"

serde = "1.0"
serde_bytes = "0.11"
serde_cbor = "0.11"

fastrand = "2.3"

canbench-rs = "0.2.1"

common = { path = "src/common" }
